name: Build and Deploy ESP8266 Firmware to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Set board platform index URL
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

    - name: Install ESP8266 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266

    - name: Install libraries
      run: |
        arduino-cli lib install "ModbusMaster"
        arduino-cli lib install "WiFiManager"
        arduino-cli lib install "ArduinoOTA"

    - name: Build firmware
      run: |
        mkdir -p firmware
        arduino-cli compile \
        --fqbn esp8266:esp8266:d1_mini_pro \
        --build-property build.flash_size=16M \
        --build-property build.flash_ld=eagle.flash.16m.ld \
        --output-dir firmware .
        cp firmware/*.bin firmware/firmware.bin


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./firmware
        enable_jekyll: false
